package StaticData;

public class LayoutData {
    public static final String PLACEHOLDERGOALS = "0";
    public static final int MAXWIDTH = 40;
    public static final String SEPARATOR = ":";
    public static final String PROMPTHOME = "Choose Home";
    public static final String PROMPTUSER = "Choose User";
    public static final String PROMPTAWAY = "Choose Away";
    public static final String ADD = "Add";
    public static final String OK = "-fx-base: lightgreen;";
    public static final String CANCEL = "-fx-background-color: coral;";
    public static final String ADDUSER = "Add User";
    public static final String DELETEUSER = "Delete User";
    public static final int USERINTERFACESPACING = 10;
    public static final int ADDMATCHPADDING = 10;
    public static final int ADDMATCHSPACING = 10;
    public static final int RESULT = 0;
    public static final int BET = 1;
    public static int WIDTH = 1150;
    public static int CENTERUSERPANEL = WIDTH/3;
    public static int HEIGHT = 700;
    public static int MAINVBOXSPACING = 10;
    public static int TABLESHBOXSPACING = 100;
    public static String TITLE = "Soccer World Cup Bet Game";
    public static String EDITUSERTITLE = "Edit Users";
    public static String FONT = "Arial";
    public static int FONTSIZE = 20;
    public static int USERMENUPADDINGBOTTOM = 50;
    public static String COLOR = "#ffffff";
    public static String IMAGEPATH = "res/background.jpg";
    public static String COLHOME = "Home";
    public static String COLAWAY = "Away";
    public static String COLGOALHOME = "Goals Home";
    public static String COLGOALAWAY = "Goals Away";
    public static String COLUSER = "User";
    public static String DELBET = "Delete selected bet";
    public static String BETTABLEHEADLINE = "Bets";
    public static String BETTABLEPLACEHOLDER = "No bets yet";
    public static String RESULTTABLEHEADLINE = "Results";
    public static String RESULTTABLEPLACEHOLDER = "No results yet";
    public static String DELRESULT = "Delete selected result";
    public static int PADDINGLEFT = 50;
    public static int PADDING = 10;
    public static int SPACING = 5;
    public static int PADDINGRIGHT = 50;
    public static int MAXLENGTH = 3;
}
